### ISSUE TITLE
Default server doesn't work

### ISSUE THREAD

**Issue by ghost** [PocketMine/RubberBand#3]
The default server doesn't work. Mine always gets
removed from the proxy.

**Comment by UserNamewwe** [comment]
Du bist ja auch Schwul du looser kanacke

**Comment by ghost** [comment]
@shoghicp, could you please remove that comment from  UserNamewwe? He said something like "You are so gay you looser".

**Comment by shoghicp** [comment]
@SuperChipsLP don't feed the troll
