### ISSUE TITLE
[SUGGESTION] Remote Tool Kit

### ISSUE THREAD

**Issue by iksaku** [PocketMine/RubberBand#5]
Well... this project is going so far... so I want to SUGGEST to add something like Remote Toll Kit from Bukkit... Here's the Bukkit plugin:

http://forums.bukkit.org/threads/admn-remotetoolkit-r10-a15-restarts-crash-detection-auto-saves-remote-console-1-6-4.674/

(This is only a SUGGESTION)

Thanks :)

**Comment by iksaku** [comment]
Obviously RubberBand need to be finished before this... if you agree @shoghicp , close this issue and add this in the "To Do" list :D

**Comment by shoghicp** [comment]
This is not the place to ask this. You can create a simple script that does that in pocketmine, and pocketmine itself supports RCon

**Comment by iksaku** [comment]
:/ I don't like RCon but okay :D I will be waiting for RubberBand
